Require dependencies explicitly
Tests were failing and we could see messages like:

app/controllers/polls_controller.rb:12: warning: toplevel constant
Answer referenced by Poll::Answer

app/controllers/polls_controller.rb:21: warning: toplevel constant
Answer referenced by Poll::Question::Answer

app/controllers/polls_controller.rb:24: warning: toplevel constant
Answer referenced by Poll::Answer

And errors in tests like:

Failure/Error: poll_answers =
::Poll::Answer.by_question(@poll.question_ids).by_author(current_user.try(:id))

NoMethodError:
       undefined method `by_question' for #<Class:0x00007fdab16c50a0>

Apparently the lookup was not correclty being performed, due to
conflicting names.

"Naming conflicts of this kind are rare in practice, but if one
occurs, require_dependency provides a solution by ensuring that
the constant needed to trigger the heuristic is defined in the
conflicting place."

https://guides.rubyonrails.org/v5.0/autoloading_and_reloading_constants.html